import { Product } from '@/types';

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'p1',
    name: 'Casque Bluetooth Sans Fil Pro',
    price: 89.99,
    original_price: 129.99,
    category: 'Electronics',
    average_rating: 4.8,
    reviews_count: 1240,
    stock: 15,
    description: 'Casque sans fil premium avec réduction de bruit active et 30 heures d\'autonomie. Idéal pour le travail et les voyages.',
    images: [{ id: '1', url: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&q=80', is_primary: true }],
  },
  {
    id: 'p2',
    name: 'Montre Minimaliste en Cuir',
    price: 149.00,
    original_price: 199.00,
    category: 'Accessories',
    average_rating: 4.6,
    reviews_count: 876,
    stock: 8,
    description: 'Montre élégante et minimaliste avec verre saphir et bracelet en cuir pleine fleur italien.',
    images: [{ id: '2', url: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&q=80', is_primary: true }],
  },
  {
    id: 'p3',
    name: 'Sérum Éclat Vitamine C',
    price: 42.00,
    original_price: 68.00,
    category: 'Beauty',
    average_rating: 4.9,
    reviews_count: 2341,
    stock: 30,
    description: 'Sérum pur à la vitamine C avec acide hyaluronique pour un teint lumineux et unifié. Testé dermatologiquement.',
    images: [{ id: '3', url: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=600&q=80', is_primary: true }],
  },
  {
    id: 'p4',
    name: 'Sneakers Runner — Édition Limitée',
    price: 120.00,
    original_price: 165.00,
    category: 'Fashion',
    average_rating: 4.7,
    reviews_count: 3200,
    stock: 12,
    description: 'Sneakers légères avec semelle en mousse réactive et tige en mesh respirant. Confort ultime pour le sport et la ville.',
    images: [{ id: '4', url: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&q=80', is_primary: true }],
  },
  {
    id: 'p5',
    name: 'Cabas en Cuir Artisanal',
    price: 199.00,
    original_price: 249.00,
    category: 'Accessories',
    average_rating: 4.8,
    reviews_count: 654,
    stock: 5,
    description: 'Cabas en cuir pleine fleur, cousu main, avec poches intérieures et quincaillerie laiton. Un objet qui dure.',
    images: [{ id: '5', url: 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=600&q=80', is_primary: true }],
  },
  {
    id: 'p6',
    name: 'Enceinte Portable 360°',
    price: 54.99,
    original_price: 79.99,
    category: 'Electronics',
    average_rating: 4.5,
    reviews_count: 987,
    stock: 20,
    description: 'Son omnidirectionnel 360° avec 20h d\'autonomie et résistance à l\'eau IPX7. Compagnon parfait pour l\'extérieur.',
    images: [{ id: '6', url: 'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=600&q=80', is_primary: true }],
  },
  {
    id: 'p7',
    name: 'Eau de Parfum Signature',
    price: 85.00,
    category: 'Beauty',
    average_rating: 4.7,
    reviews_count: 1890,
    stock: 25,
    description: 'Fragrance exclusive aux notes de bergamote, cèdre et ambre chaud. Flacon 50ml.',
    images: [{ id: '7', url: 'https://images.unsplash.com/photo-1588515724527-074a7a56616c?w=600&q=80', is_primary: true }],
  },
  {
    id: 'p8',
    name: 'Lunettes de Soleil Polarisées',
    price: 175.00,
    original_price: 220.00,
    category: 'Accessories',
    average_rating: 4.6,
    reviews_count: 543,
    stock: 7,
    description: 'Verres polarisés UV400 avec monture en titane. Livrées avec étui et chiffon de nettoyage.',
    images: [{ id: '8', url: 'https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=600&q=80', is_primary: true }],
  },
  {
    id: 'p9',
    name: 'Appareil Photo Instantané',
    price: 95.00,
    original_price: 120.00,
    category: 'Electronics',
    average_rating: 4.4,
    reviews_count: 421,
    stock: 10,
    description: 'Appareil photo rétro avec flash intégré, retardateur et mode double exposition. L\'art de l\'instant figé.',
    images: [{ id: '9', url: 'https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?w=600&q=80', is_primary: true }],
  },
];

export const CATEGORIES = ['All', 'Electronics', 'Beauty', 'Accessories', 'Fashion', 'Home'];
