import { Product } from '@/types';

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'p1',
    name: 'Wireless Noise-Cancelling Headphones',
    price: 89.99,
    original_price: 129.99,
    category: 'Electronics',
    average_rating: 4.8,
    reviews_count: 1240,
    stock: 15,
    description: 'Premium wireless headphones with active noise cancellation and 30-hour battery life. Perfect for work and travel.',
    images: [{ id: '1', url: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&q=80', is_primary: true }],
  },
  {
    id: 'p2',
    name: 'Minimalist Leather Watch',
    price: 149.00,
    original_price: 199.00,
    category: 'Accessories',
    average_rating: 4.6,
    reviews_count: 876,
    stock: 8,
    description: 'Elegant minimalist watch with sapphire crystal glass and Italian full-grain leather strap.',
    images: [{ id: '2', url: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&q=80', is_primary: true }],
  },
  {
    id: 'p3',
    name: 'Vitamin C Brightening Serum',
    price: 42.00,
    original_price: 68.00,
    category: 'Beauty',
    average_rating: 4.9,
    reviews_count: 2341,
    stock: 30,
    description: 'Pure vitamin C serum with hyaluronic acid for radiant, even-toned skin. Dermatologist tested.',
    images: [{ id: '3', url: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=600&q=80', is_primary: true }],
  },
  {
    id: 'p4',
    name: 'Runner Sneakers — Limited',
    price: 120.00,
    original_price: 165.00,
    category: 'Fashion',
    average_rating: 4.7,
    reviews_count: 3200,
    stock: 12,
    description: 'Lightweight running sneakers with responsive foam cushioning and breathable mesh upper.',
    images: [{ id: '4', url: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&q=80', is_primary: true }],
  },
  {
    id: 'p5',
    name: 'Handcrafted Leather Tote',
    price: 199.00,
    original_price: 249.00,
    category: 'Accessories',
    average_rating: 4.8,
    reviews_count: 654,
    stock: 5,
    description: 'Handcrafted full-grain leather tote with interior organization pockets and brass hardware.',
    images: [{ id: '5', url: 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=600&q=80', is_primary: true }],
  },
  {
    id: 'p6',
    name: 'Portable Bluetooth Speaker',
    price: 54.99,
    original_price: 79.99,
    category: 'Electronics',
    average_rating: 4.5,
    reviews_count: 987,
    stock: 20,
    description: '360° omnidirectional sound with 20-hour battery and IPX7 waterproof rating.',
    images: [{ id: '6', url: 'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=600&q=80', is_primary: true }],
  },
  {
    id: 'p7',
    name: 'Signature Eau de Parfum',
    price: 85.00,
    category: 'Beauty',
    average_rating: 4.7,
    reviews_count: 1890,
    stock: 25,
    description: 'Exclusive fragrance with notes of bergamot, cedar and warm amber. 50ml.',
    images: [{ id: '7', url: 'https://images.unsplash.com/photo-1588515724527-074a7a56616c?w=600&q=80', is_primary: true }],
  },
  {
    id: 'p8',
    name: 'Polarized Sunglasses',
    price: 175.00,
    original_price: 220.00,
    category: 'Accessories',
    average_rating: 4.6,
    reviews_count: 543,
    stock: 7,
    description: 'UV400 polarized lenses with titanium frames. Includes case and cloth.',
    images: [{ id: '8', url: 'https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=600&q=80', is_primary: true }],
  },
  {
    id: 'p9',
    name: 'Instant Film Camera',
    price: 95.00,
    original_price: 120.00,
    category: 'Electronics',
    average_rating: 4.4,
    reviews_count: 421,
    stock: 10,
    description: 'Retro-style instant camera with built-in flash, self-timer, and double exposure mode.',
    images: [{ id: '9', url: 'https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?w=600&q=80', is_primary: true }],
  },
];

export const CATEGORIES = ['All', 'Electronics', 'Beauty', 'Accessories', 'Fashion', 'Home'];
